type Post {
    _id: ID!
    title: String!
    content: String!
    author: User!
}

input UserInput {
    title: String!
    content: String!
    author: ID!
}

type Query {
    posts: [Post!]!
    post(id: ID!): Post!
}

type Mutation {
    createPost(data: UserInput!): User!
    updatePost(id: ID, data: UserInput!): User!
    deletePost(id: ID!): Boolean
}